/**
 * CRE Workflow: Register
 * 
 *
 * Generated by Scaffold CRE — https://github.com/tigeragentt/scaffold-cre
 *
 * TODOs in this file:
 * - Fill in function arguments for EVM read/write calls
 * - Define request/response types for HTTP capabilities
 * - Add your consensus aggregation strategy
 * - Replace placeholder contract addresses in config.json
 */
import {
  cre,
  getNetwork,
  type Runtime,
  EVMClient,
  TxStatus,
  CronCapability,
  type CronPayload,
  hexToBase64,
  bytesToHex
} from '@chainlink/cre-sdk'
import { type Address, encodeFunctionData, parseAbi, parseAbiParameters, encodeAbiParameters, decodeFunctionResult } from 'viem'
import { z } from 'zod'

// ─── Config ────────────────────────────────────────────────────────────────
// Values come from config.json — edit that file, not here.

export const configSchema = z.object({
  schedule: z.string(),
  chainSelectorName: z.string(),
  registerUsingCRESolAddress: z.string(),
  gasLimit: z.string(),
})

type Config = z.infer<typeof configSchema>


// ─── EVM Client (module-level, initialized in initWorkflow) ────────────────
let network: ReturnType<typeof getNetwork>
let evmClient: EVMClient

// ─── Local Execution ───────────────────────────────────────────────────────


// ─── Handlers ──────────────────────────────────────────────────────────────

export function onACada5Min(runtime: Runtime<Config>, payload: CronPayload): string {
  if (!payload.scheduledExecutionTime) throw new Error('Missing scheduledExecutionTime')
  runtime.log('A cada 5 min triggered at ' + payload.scheduledExecutionTime)

    // ── EVM WRITE: RegisterUsingCRE.sol.registerSet ─────
    const reportPayload = encodeAbiParameters(
      parseAbiParameters('string myinfo'), // TODO: match your contract's onReport param types
      ["$Comprem Bitcoin!$"],                                // TODO: fill actual report data
    )
    const report = runtime.report({
      encodedPayload: hexToBase64(reportPayload),
      encoderName: 'evm',
      signingAlgo: 'ecdsa',
      hashingAlgo: 'keccak256',
    }).result()
    const writeResult = evmClient
      .writeReport(runtime, {
        receiver: runtime.config.registerUsingCRESolAddress as `0x${string}`,
        report,
        gasConfig: { gasLimit: runtime.config.gasLimit },
      })
      .result()
    if (writeResult?.txStatus !== TxStatus.SUCCESS) {
      throw new Error(`EVM write failed: ${writeResult?.errorMessage}`)
    }
    runtime.log(`RegisterUsingCRE.sol.registerSet tx: ${bytesToHex(writeResult.txHash || new Uint8Array(32))}`)
  // TODO: return a result string
  return 'ok'
}

// ─── Init ──────────────────────────────────────────────────────────────────

export function initWorkflow(config: Config) {

  network = getNetwork({
    chainFamily: 'evm',
    chainSelectorName: config.chainSelectorName,
    isTestnet: true,
  })
  if (!network) throw new Error(`Network not found: ${config.chainSelectorName}`)
  evmClient = new EVMClient(network.chainSelector.selector)
  const cronTrigger = new CronCapability()

  return [
    cre.handler(cronTrigger.trigger({ schedule: config.schedule }), onACada5Min),
  ]
}
